# Generated by Django 5.2.1 on 2025-05-23 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(choices=[(1, '1° Bachillerato'), (2, '2° Bachillerato'), (3, '3° Bachillerato')], default=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exercises', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('addition_exercises', models.IntegerField(default=0)),
                ('addition_correct', models.IntegerField(default=0)),
                ('subtraction_exercises', models.IntegerField(default=0)),
                ('subtraction_correct', models.IntegerField(default=0)),
                ('multiplication_exercises', models.IntegerField(default=0)),
                ('multiplication_correct', models.IntegerField(default=0)),
                ('division_exercises', models.IntegerField(default=0)),
                ('division_correct', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
